<?php

require_once __DIR__."/model_base.php";

class model_registration extends model_base
{
    public $rules=[
        'login'=>['unique', 'required' ],
        'email'=>['unique', 'required'],
        'tel'=>['unique', 'required'],
        'password'=>['required'],
        ];
    public $table='users';


    public function test(){
        echo "".print_r($_POST)."";
    }

    public function validate($rules=null, $table=null)
    {
        parent::validate($this->rules, $this->table); // TODO: Change the autogenerated stub
    }

    public function addUser(){
        $query="INSERT INTO {$this->table} (email, login, tel, password) VALUES ('".$_POST['email']."','".$_POST['login']."','".$_POST['tel']."','".$_POST['password']."')";
        if($this->data_base->query($query)!=true){
            echo "Ошибка";
        }
    }
}